project:
  type: website
  output-dir: docs

website:
  title: "szlo.ai"
  navbar:
    background: "#050505"
    right:
      - text: "Posts"
        file: index.qmd
      - about.qmd
      - research.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: ayu
    code-line-numbers: true

editor: visual

